CREATE TABLE ENBA_T_J4U_REGION_CELLID_MAP (
   POOL_ID varchar(15 bytes) NOT NULL,
   CELL_ID  varchar(15 bytes) NOT NULL,
   START_DATE timestamp,
   END_DATE timestamp,
   ENABLED tinyint default 0,
   LOAD_DATE timestamp DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT PK_ENBA_T_J4U_REGION_CELLID_MAP PRIMARY KEY (POOL_ID, CELL_ID)
	);

	CREATE TABLE ECMP_T_LOCATION_PROD_INFO (
	   PRODUCT_ID varchar(80 bytes) NOT NULL,
	   PRODUCT_DESC varchar(80) NOT NULL,
	   LANG_CODE integer NOT NULL,
	   PRODUCT_TYPE varchar(30 bytes),
	   PRODUCT_SUBTYPE varchar(30 bytes),
	   ACTIVE_FLAG varchar(1 bytes) DEFAULT 'Y',
	   PRODUCT_CODE varchar(80 bytes),
	   REFRESH_DATE timestamp,
	   B_VALUE varchar(30 bytes),
	   C_VALUE varchar(30 bytes),
	   POOL_ID varchar(15 bytes) NOT NULL
	);

CREATE TABLE ENBA_T_J4U_ML_LOCATION_OFFER (
   MSISDN varchar(15 bytes) NOT NULL,
   PRODUCT_ID varchar(10 bytes) NOT NULL,
   PRODUCT_TYPE varchar(30 bytes),
   PRODUCT_SUBTYPE varchar(30 bytes),
   LOAD_DATE timestamp,
   PRODUCT_PRICE varchar(20 bytes),
   OFFER_RANK integer,
   EXPECTED_VALUE varchar(20 bytes),
   CONSTRAINT PK_ENBA_T_J4U_ML_LOCATION_OFFER PRIMARY KEY (MSISDN, PRODUCT_ID, PRODUCT_TYPE)
	);
	PARTITION TABLE ENBA_T_J4U_ML_LOCATION_OFFER ON COLUMN MSISDN;

CREATE TABLE ECMP_T_PRODUCT_PRICE (
   PRODUCT_ID varchar(10) NOT NULL,
   PRODUCT_PRICE varchar(30) NOT NULL,
   PRODUCT_TYPE varchar(30),
   LOAD_DATE varchar(30),
   CONSTRAINT PK_ECMP_T_PRODUCT_PRICE PRIMARY KEY (PRODUCT_ID)
);
PARTITION TABLE ECMP_T_PRODUCT_PRICE ON COLUMN PRODUCT_ID;

--procedures

CREATE PROCEDURE ENBA_P_J4U_ML_LOCATION_OFFER
   PARTITION ON TABLE ENBA_T_J4U_ML_LOCATION_OFFER COLUMN MSISDN PARAMETER 1
   AS
   select EXPECTED_VALUE, PRODUCT_ID, PRODUCT_PRICE from ENBA_T_J4U_ML_LOCATION_OFFER where PRODUCT_TYPE=? and MSISDN = ?;


CREATE procedure P_GET_REGION_ID_BY_CELL_ID
as
SELECT POOL_ID FROM ENBA_T_J4U_REGION_CELLID_MAP WHERE CELL_ID = ?;


CREATE PROCEDURE ENBA_P_GET_LOCATION_PRODUCT_INFO
   AS
 select PRODUCT_ID, B_VALUE, C_VALUE, PRODUCT_DESC from ECMP_T_LOCATION_PROD_INFO
 where PRODUCT_TYPE = ? and LANG_CODE = ? and POOL_ID = ? and PRODUCT_ID in ?;

insert into ECMP_T_COMMS_TEMPLATE (TEMPLATE_ID,LANG_CODE,TEMPLATE,OFFER_ORDER_CSV)
values('ML_HOURLY_DATA_2OFFER_MENU',2,'1)@ProdId_1@
2)@ProdId_2@','ProdId_1,ProdId_2');

insert into ECMP_T_COMMS_TEMPLATE (TEMPLATE_ID,LANG_CODE,TEMPLATE,OFFER_ORDER_CSV)
values('ML_HOURLY_DATA_1OFFER_MENU',2,'1)@ProdId_1@','ProdId_1');



CREATE PROCEDURE ECMP_P_GET_PRODUCT_PRICE
   AS
   select PRODUCT_ID, PRODUCT_PRICE from ECMP_T_PRODUCT_PRICE where PRODUCT_ID in ?;





CREATE PROCEDURE USSD_P_ML_OFFER_SELECT
   PARTITION ON TABLE ENBA_T_J4U_ML_OFFER COLUMN MSISDN
   AS
   select PRODUCT_ID, EXPECTED_VALUE from ENBA_T_J4U_ML_OFFER where MSISDN = ? and PRODUCT_TYPE = ? and convert(PRODUCT_PRICE,float) <= ? order by cast(EXPECTED_VALUE as decimal) DESC limit 3;

CREATE PROCEDURE USSD_P_ML_OFFER_SELECT_BY_EXPVAL
   PARTITION ON TABLE ENBA_T_J4U_ML_OFFER COLUMN MSISDN
   AS
   select PRODUCT_ID, EXPECTED_VALUE from ENBA_T_J4U_ML_OFFER where MSISDN = ? and PRODUCT_TYPE = ? and PRODUCT_ID not in ? order by cast(EXPECTED_VALUE as decimal) DESC limit ?;


CREATE PROCEDURE USSD_P_ML_OFFER_MSG_UPSERT
   PARTITION ON TABLE ENBA_T_J4U_ML_OFFER_MSG COLUMN MSISDN
   AS
   UPSERT into ENBA_T_J4U_ML_OFFER_MSG values (? , ? , ?, ?, ?, ?);

CREATE PROCEDURE USSD_P_ERED_T_REDUCED_CCR_SELECT
   PARTITION ON TABLE ERED_T_REDUCED_CCR COLUMN MSISDN
   AS
   select ML_CUSTOMER_FLAG, RANDOM_FLAG, LANG_CODE, OFFER_REFRESH_FLAG, J4U_ELIGIBILITY, A_VALUE from ERED_T_REDUCED_CCR where MSISDN = ?;



select EXPECTED_VALUE, PRODUCT_ID, PRODUCT_PRICE from ENBA_T_J4U_ML_LOCATION_OFFER
where PRODUCT_TYPE='J4U Integrated & SMS' and MSISDN = '43816975892';


CREATE STREAM ECMP_T_J4U_API_LOG PARTITION ON COLUMN TRANSACTION_ID EXPORT TO TARGET ECMP_CONN (
   TRANSACTION_ID varchar(80 bytes) NOT NULL,
   MSISDN varchar(16 bytes),
   API_TYPE varchar(20 bytes),
   STATUS varchar(40 bytes),
   PRODUCT_TYPE varchar(20 bytes),
   PRODUCT_IDS varchar(80 bytes),
   SELECTED_PRODUCT_ID varchar(20 bytes),
   CUSTOMER_BALANCE varchar(20 bytes),
   ML_CUSTOMER_FLAG varchar(1 bytes),
   RANDOM_FLAG varchar(1 bytes),
   DATE_TIME timestamp,
   COMMENTS varchar(200 bytes),
   REF_NUM varchar(50 bytes),
   THIRD_PARTY_REF varchar(20 bytes),
   CHANNEL varchar(10 bytes),
   CELL_ID varchar(15 bytes),
   POOL_ID varchar(15 bytes)
);

create procedure ECMP_T_J4U_API_LOG_INSERT
as
insert into ECMP_T_J4U_API_LOG (TRANSACTION_ID varchar(80) NOT NULL,
   MSISDN,
   API_TYPE ,
   STATUS ,
   PRODUCT_TYPE,
   PRODUCT_IDS ,
   SELECTED_PRODUCT_ID ,
   CUSTOMER_BALANCE ,
   ML_CUSTOMER_FLAG ,
   RANDOM_FLAG,
   DATE_TIME ,
   COMMENTS ,
   REF_NUM ,
   THIRD_PARTY_REF, CHANNEL) into(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

CREATE TABLE ENBA_T_J4U_ML_OFFER (
   MSISDN varchar(15) NOT NULL,
   PRODUCT_ID varchar(10) NOT NULL,
   PRODUCT_TYPE varchar(30),
   PRODUCT_SUBTYPE varchar(30),
   LOAD_DATE timestamp,
   PRODUCT_PRICE varchar(20),
   OFFER_RANK integer,
   EXPECTED_VALUE varchar(20),
   CONSTRAINT PK_ENBA_T_J4U_ML_OFFER PRIMARY KEY (MSISDN, PRODUCT_ID, PRODUCT_TYPE)
);
PARTITION TABLE ENBA_T_J4U_ML_OFFER ON COLUMN MSISDN;
CREATE PROCEDURE USSD_P_ML_OFFER_MSG_SELECT
   PARTITION ON TABLE ENBA_T_J4U_ML_OFFER_MSG COLUMN MSISDN
   AS
   select PRODUCT_IDS, MENU_CONTENT, RF_VALUE from  ENBA_T_J4U_ML_OFFER_MSG where MSISDN = ? and SUB_MENU_TYPE = ?;

---changed to 1 query parameter
CREATE PROCEDURE ECMP_P_GET_PRODUCT_PRICE
   AS
   select PRODUCT_ID, PRODUCT_PRICE from ECMP_T_PRODUCT_PRICE where PRODUCT_ID in ?;

insert into ERED_T_REDUCED_CCR( MSISDN, ML_CUSTOMER_FLAG, RANDOM_FLAG, LANG_CODE , OFFER_REFRESH_FLAG, J4U_ELIGIBILITY, A_VALUE)
 values('816975891', 'Y', 'N', '2', 'VDIH', 'Y', '0.00001');

update  ERED_T_REDUCED_CCR set OFFER_REFRESH_FLAG='VDIH' where MSISDN='816975892';

update  ENBA_T_J4U_ML_LOCATION_OFFER set MSISDN='243816975892' where MSISDN='43816975892';
61090, 61091, 61092]

insert into ECMP_T_PRODUCT_PRICE (PRODUCT_ID, PRODUCT_TYPE, PRODUCT_PRICE) values('61090', 'J4U Data', '160000');
insert into ECMP_T_PRODUCT_PRICE (PRODUCT_ID, PRODUCT_TYPE, PRODUCT_PRICE) values('61091', 'J4U Data', '150000');
insert into ECMP_T_PRODUCT_PRICE (PRODUCT_ID, PRODUCT_TYPE, PRODUCT_PRICE) values('61092', 'J4U Data', '200000');